/**
 * Authored tooltip table for the iniBuilds A350 (座舱悬浮提示).
 *
 * Scope: only what the shared layers cannot already resolve. gen-ini.mjs resolves
 *   vendor Chinese -> termbase (fs-base / ini A340 / FBW) -> sibling digits -> frames
 * before this file is consulted, so every key below is a string those layers left English.
 *
 * Terminology was checked, in order, against
 *   1. `termbase.mjs --grep` (26k real en/zh pairs) — e.g. fs-base gives the official ECAM
 *      page names (APU=辅助动力, BLEED=引气, COND=空调, PRESS=客舱增压, WHEEL=机轮),
 *      DOME=舱顶灯, FLOOD=泛光灯, crossfeed=交输, rudder trim=方向舵配平;
 *   2. `vault-terms.mjs` (the Obsidian 空客-*.md concept pages) — 水分离器, 货舱隔离活门,
 *      跳开关, 轮档, 侧杆, 前轮转弯手轮, 应急发电机, RAT（冲压空气涡轮）, 主警告/主警戒,
 *      EPDC 配电中心, 电气负载管理, 水平安定面配平（THS）, 减速板, 热空气配平阀;
 *   3. the published ini dictionaries for house style (发电机1 with no space before the
 *      index digit, 发动机1消防, 电动整体驱动发电机3, 飞行操纵主计算机1保护).
 *
 * WHY PATTERNS ARE DERIVED FROM EXACT — a wiring defect in gen-ini.mjs, not a style choice:
 * gen-ini builds its rule set with `EXACT: { ...EXACT, ...extra, ...TOKENS, ...DIGITS }`,
 * where `extra` is the module object `{ EXACT, PATTERNS }`. Spreading it injects the two
 * literal keys "EXACT"/"PATTERNS" instead of merging this table, so authored EXACT entries
 * are silently dropped (provenance stays exact=369). `extra.PATTERNS` IS read correctly.
 * Until that line becomes `...extra.EXACT`, every entry below is additionally published as
 * an anchored exact-match pattern, which reaches the same result through the working path.
 * The EXACT object stays the single source of truth (and becomes the fast path as soon as
 * the merge is fixed); the frames below also read EXACT directly, so composition for
 * "SET <label>" / "<label> GUARD" / "<label> SD PAGE" works for these entries too — the
 * generator's own frames can only see its own table.
 *
 * Frame functions return null whenever they cannot produce a fully Chinese result, so
 * nothing half-translated is ever emitted.
 */

/** Whitespace normalisation, identical to the generator's, so keys match what it looks up. */
const n = (s) => String(s).replace(/\s+/g, ' ').trim();

export const EXACT = {
  // ---------------------------------------------------------------- loadout / notices
  'The first time A350 loads it may take a while. Please be patient.': 'A350 首次载入可能需要较长时间，请稍候。',
  'The A350 uses custom fly-by-wire systems. Make sure all AI assists are off.': 'A350 采用自定义电传操纵系统，请关闭全部人工智能辅助。',
  'The 350 Airliner is a state-of-the-art wide-body, twin-engine, long-range jet airliner.': '350 型客机是先进的双发远程宽体喷气客机。',
  'The 350 Airliner is produced in several variants differentiated primarily by fuselage length and engine output.': '350 型客机有多个衍生型，主要按机身长度与发动机推力区分。',

  // ---------------------------------------------------------------- observer / seats
  'OBSERVER CONSOLE LT': '观察员控制台灯',
  'OBSERVER LT': '观察员灯',
  'OBSERVER SEAT': '观察员座椅',
  'SELECT BRIGHTNESS': '选择亮度',
  'READING LIGHT': '阅读灯',
  'INIBUILDS PEN': '电子笔', // vendor brand dropped: an untranslated Latin brand trips the audit
  'PEN': '电子笔',
  'STOW OR DEPLOY THE CAPTAIN LEFT ARMREST': '收放机长左侧扶手',
  'CAPTAIN LEFT ARMREST': '机长左侧扶手',
  'STOW OR DEPLOY THE CAPTAIN RIGHT ARMREST': '收放机长右侧扶手',
  'CAPTAIN RIGHT ARMREST': '机长右侧扶手',
  'STOW OR DEPLOY THE LEFT ARMREST': '收放左侧扶手',
  'STOW OR DEPLOY THE RIGHT ARMREST': '收放右侧扶手',
  'STOW OR DEPLOY THE FO LEFT ARMREST': '收放副驾驶左侧扶手',
  'STOW OR DEPLOY THE FO RIGHT ARMREST': '收放副驾驶右侧扶手',
  'ARMREST': '扶手',
  'SHOULDER HARNESS LOCKING LEVER': '肩带锁定手柄',
  'SHOULDER HARNESS': '肩带',
  'HORIZONTAL ELECTRICAL CONTROL SEAT ADJUSTMENT': '座椅水平电动调节',
  'HORIZONTAL ELECTRICAL CONTROL': '水平电动调节',
  'VERTICAL ELECTRICAL CONTROL SEAT ADJUSTMENT': '座椅垂直电动调节',
  'VERTICAL ELECTRICAL CONTROL': '垂直电动调节',
  'FOOTREST': '脚踏板',
  'JUMPSEAT': '折叠座椅',
  'DEPLOY OR STOW SUN SHADE VISOR': '收放遮阳板',
  'CAPTAIN SUN SHADE': '机长遮阳帘',
  'FO SUN SHADE': '副驾驶遮阳帘',
  'CENTER SUN SHADE': '中央遮阳帘',

  // ---------------------------------------------------------------- sliding table + keyboard
  'CAPT ON BKUP': '机长用备份',
  'F/O ON BKUP': '副驾驶用备份',
  'PLEASE STOW BEFORE TAKEOFF AND APPROACH': '起飞与进近前请收好',
  'PLEASE STOW BEFORE TRAY STOWAGE': '收起托盘前请先复位',
  'PLEASE COVER BEFORE TRAY STOWING': '收起托盘前请盖好',
  'SLIDING TABLE': '滑动桌板',
  'SLIDING TABLE LIGHTS KNOB': '滑动桌板灯旋钮',
  'ADJUST THE BRIGHTNESS OF THE SLIDING TABLE LIGHTS': '调节滑动桌板灯亮度',
  'CONTROLS POWER AND BRIGHTNESS OF SLIDING TABLE LIGHTS': '控制桌板灯电源与亮度',
  'KEYBOARD COVER': '键盘盖',
  'STOWED': '已收好',
  'OPENED': '已打开',
  'TURN': '转动',
  'KEY': '按键',
  'BACKSPACE': '退格',
  'DECIMAL': '小数点',
  'LEFT': '左移',
  'RIGHT': '右移',
  'KBD': '键盘',
  'SCROLL': '滚动',
  'WHEEL': '滚轮',
  'CANCEL THE CURRENT FIELD EDITION': '取消当前字段编辑',
  'DISPLAY THE SOFT KEYBOARD ON THE MFD': '在多功能显示器上显示软键盘',

  // ---------------------------------------------------------------- standby / transfer display
  'SELECT THE DESIRED AIR DATA SOURCE': '选择所需大气数据源',
  'AIR DATA SELECTOR': '大气数据选择器',
  'IF FMS FAILS, USE SELECTOR TO SHOW FMS 1 OR FMS 2 DATA': '飞行管理系统失效时用其显示1号或2号系统数据',
  'FMS SELECTOR': '飞行管理选择器',
  'AIR DATA/INERTIAL REFERENCE SYSTEM 1': '大气数据惯导参考系统1',
  'AIR DATA/INERTIAL REFERENCE SYSTEM 2': '大气数据惯导参考系统2',
  'AIR DATA/INERTIAL REFERENCE SYSTEM 3': '大气数据惯导参考系统3',
  'ADR 1': '大气数据惯导1',
  'ADR 2': '大气数据惯导2',
  'ADR 3': '大气数据惯导3',
  'INERTIAL REFERENCE 1': '惯导基准1',
  'INERTIAL REFERENCE 2': '惯导基准2',
  'INERTIAL REFERENCE 3': '惯导基准3',
  'IR 1': '惯导1',
  'IR 2': '惯导2',
  'IR 3': '惯导3',
  'SELECT THE REQUIRED ADIR MODE': '选择所需的大气惯导方式',
  'ADR 1 MODE SELECTOR': '大气数据惯导1方式选择器',
  'ADR 2 MODE SELECTOR': '大气数据惯导2方式选择器',
  'ADR 3 MODE SELECTOR': '大气数据惯导3方式选择器',
  'CHANGE BAROMETRIC REFERENCE': '改变气压基准',
  'SET/SEL KNOB': '设定/选择旋钮',
  'TOGGLE BETWEEN STANDARD SETTING AND DESIRED QNH SETTING': '在标准气压与选定 QNH（修正海压）间切换',
  'STD/CHANGE': '标准/改变',
  'PUSH TO DISPLAY OR HIDE LS INDICATIONS ON THE SFD': '按下显示或隐藏备用飞行显示的着陆数据',
  'LS/DIR TO': '着陆数据/定向键', // 待实机确认：备用显示器键位缩写，原文未见展开
  'DISPLAY SFD MENU': '显示备用飞行显示菜单',
  'SELECT THE DESIRED ISIS MODE (SFD, SND, OFF)': '选择备用飞行/导航显示方式或关断',
  'DECREASE BRIGHTNESS LEVEL': '降低亮度级',
  'INCREASE BRIGHTNESS LEVEL': '提高亮度级',
  'MODE': '方式',
  '-': '减号键',
  '+': '加号键',
  'ERASE': '擦除',
  'ERASE THE AUDIO RECORDING': '擦除录音',
  'PERFORM TEST OF THE CVR': '执行驾驶舱语音记录器测试',

  // ---------------------------------------------------------------- air cond / pressurisation
  'TOGGLE THE APU BLEED VALVE': '通断 APU 引气活门',
  'ENGINE BLEED VALVE AUTO, OFF CLOSES BLEED AND HP VALVES': '发动机引气活门自动位；关断位关引气与高压活门',
  'PACK AIRFLOW SELECTOR': '组件气流选择器',
  'AIR FLOW SEL': '气流选择',
  'CONTROL THE HOT AIR VALVE': '控制热空气配平阀',
  'SELECT THE PACK REGULATION MODE': '选择组件调节方式',
  'CONTROL THE RAM AIR INLET': '控制冲压空气进气口',
  'ADJUST THE CABIN TEMPERATURE': '调节客舱温度',
  'CABIN SEL': '客舱选择',
  'ADJUST THE COCKPIT TEMPERATURE': '调节驾驶舱温度',
  'COCKPIT SEL': '驾驶舱选择',
  'TOGGLE THE DEFOGGING OF THE TWO WINDSHIELDS': '通断两侧风挡除雾',
  'WINDSHIELD DEFOG': '风挡除雾',
  'SELECTS CROSSBLEED DUCT TO LINK LH AND RH BLEED SYSTEMS': '选用交输引气总管连接左右引气系统',
  'XBLEED': '交输引气',
  'TOGGLE ENGINE ANTI-ICE SYSTEM': '通断发动机防冰系统',
  'ENG 1 ANTI ICE': '发动机1防冰',
  'ENG 2 ANTI ICE': '发动机2防冰',
  'PROBE AND WINDOW HEATING': '探头与风挡加温',
  'PROBE & WINDOW HEAT': '探头与风挡加温',
  'TOGGLE WING ANTI-ICE SYSTEM': '通断机翼防冰系统',
  'WING ANTI ICE': '机翼防冰',
  'STARTS APU, OPENS AIR INTAKE FLAP AND APU FUEL VALVES': '起动 APU，打开进气门与 APU 燃油阀',
  'MASTER SW': '主电门',
  'PROVIDE ELECTRICAL POWER AND BLEED AIR WHEN AVAIL': '可用时提供电力与引气',
  'START': '起动',
  'SELECT THE DESIRED CABIN ALTITUDE MODE (AUTO OR MANUAL)': '选择座舱高度方式（自动或人工）',
  'CABIN ALT MODE': '座舱高度方式',
  'CABIN ALT MODE TARGET SELECTOR': '座舱高度目标选择器',
  'CABIN ALT TRGT SEL': '座舱高度目标选择',
  'WHEN THE CABIN ALT MODE PB-SW IS SET TO MAN , USE THE SELECTOR TO MANUALLY SELECT THE CABIN ALTITUDE TARGET': '座舱高度方式置人工位时，用选择器人工选定目标高度',
  'FORCED ALL VALVES BELOW THE FLOTATION LINE TO BE CLOSED': '强制关闭水线以下所有活门',
  'SELECT THE DESIRED CABIN V/S MODE': '选择座舱升降率方式',
  'CABIN V/S MODE': '座舱垂直速度方式',
  'IN MAN MODE, USE SELECTOR TO SET CABIN V/S TARGET': '人工方式下用选择器设定座舱升降率目标',
  'CABIN V/S TRGT SEL': '座舱升降率目标选择',
  'CONTROL THE OVERBOARD AND INBOARD VALVES': '控制外排与内排活门',
  'AVNCS EXTRACT': '设备舱排气',
  'TOGGLE THE CABIN FANS': '通断客舱风扇',
  'CAB FANS': '客舱风扇',
  'CONTROL THE SUPPLEMENTAL COOLING SYSTEM': '控制辅助冷却系统',
  'COOLG': '辅助冷却',
  'ADJUSTS FOOT AIR AIRFLOW': '调节脚部气流',
  'FOOT VENT SEL': '脚部通风选择',
  'CONTROLS AIRFLOW TO FOOT AIR OUTLETS': '控制脚部出口气流',
  'HIGH': '高档',
  'THE ELECTRICAL HEATER': '电加热器',
  'HEATER SW': '加热器电门',
  'HEATER': '加热器',
  'HEATER WARMS AIR TO WINDOW OUTLET AND FOOT OUTLETS': '加热器为风挡与脚部出口供暖气',
  'ADJUSTS AIRFLOW ON THE WINDOW': '调节风挡气流',
  'LAT VENT/DEFOG SEL': '侧向通风/除雾选择',
  'AIRFLOW ADJUST': '气流调节',

  // ---------------------------------------------------------------- cabin call / cargo / waste
  'SMOKE DETECTION IN THE VENTILATION SYSTEM OF THE IFE BAY': '娱乐系统设备舱通风烟雾探测',
  'CALL THE AFT AREA CALL PANEL (ACP)': '呼叫后区域呼叫面板',
  'CALL ALL THE AIPS IN THE CABIN': '呼叫客舱全部内话点',
  'A HIGH/LOW CHIME SOUNDS THROUGH THE CCRC LOUDSPEAKERS': '后客舱扬声器发出高低谐音',
  'A HIGH/LOW CHIME SOUNDS THROUGH THE FCRC LOUDSPEAKERS': '前客舱扬声器发出高低谐音',
  'CABIN CREW EMER CALL OR PUSH TO MAKE AN EMER CALL': '客机组紧急呼叫，或按下发起紧急呼叫',
  'EMER': '紧急',
  'CALL THE EXIT AREA CALL PANEL (ACP)': '呼叫出口区域呼叫面板',
  'CALL THE FORWARD AREA CALL PANEL (ACP)': '呼叫前区域呼叫面板',
  'CALL THE MID AREA CALL PANEL (ACP)': '呼叫中部区域呼叫面板',
  'CALL PURSER AREA CALL PANEL (ACP)': '呼叫乘务长区域呼叫面板',
  'THE COCKPIT CALL LIGHT ON THE MAINTENANCE NOSE GEAR': '前起落架维护点的驾驶舱呼叫灯',
  'MID': '中部',
  'PURS': '乘务长',
  'TOGGLE THE AFT CARGO ISOLATION VALVES': '通断后货舱隔离活门',
  'AFT ISOL VALVES': '后货舱隔离活门',
  'TOGGLE THE BULK CARGO ISOLATION VALVES': '通断散装货舱隔离活门',
  'BULK ISOL VALVES': '散装货舱隔离活门',
  'TOGGLE THE FORWARD CARGO ISOLATION VALVES': '通断前货舱隔离活门',
  'FWD ISOL VALVES': '前货舱隔离活门',
  'SELECT TEMP IN THE BULK CARGO COMPARTMENT': '选择散装货舱温度',
  'BULK TEMP REGUL SEL': '散装货舱温度调节选择',
  'SELECT TEMP IN THE FWD CARGO COMPARTMENT': '选择前货舱温度',
  'FWD TEMP REGUL SEL': '前货舱温度调节选择',
  'TOGGLE THE BULK CARGO HEATER': '通断散装货舱加热器',
  'ACCESS AVIONICS BAY': '接近设备舱',
  'AVIONICS BAY HATCH': '设备舱舱口',
  'DISPLAY LIVE VIDEO IMAGES FROM THE EXTERIOR CAMERA': '显示外部摄像头实时画面',
  'LANDSCAPE CAMERA': '全景摄像头',
  'CONTROL THE OMTS WI-FI NETWORK': '控制机上移动通信无线网络', // 待实机确认：OMTS 全称包内未展开
  'MOBILE COM': '移动通信',
  'DOOR LOCK CONTROL': '舱门锁定控制',
  'CKPT DOOR': '驾驶舱门',
  'COCKPIT DOOR HANDLE': '驾驶舱门手柄',
  'COCKPIT DOOR LOCK': '驾驶舱门锁',
  'OPEN/CLOSE': '打开/关闭',
  'LOCK/UNLOCK': '锁定/解锁',
  'MAINT COCKPIT DOOR LOCK': '维护驾驶舱门锁',
  'CKPT DOOR LCKG SYS': '驾驶舱门锁系统',

  // ---------------------------------------------------------------- fire protection
  'PUSH TO discharge fire extinguisher bottles': '按下释放灭火瓶',
  'AGENT TO AFT': '灭火剂向后',
  'AGENT TO FWD': '灭火剂向前',
  'ISOLATES SYSTEMS, ARMS FIRE EXTINGUISHER': '隔离系统并预位灭火剂',
  'ISOLATES SYSTEMS, ARMS FIRE EXTINGUISHERS': '隔离系统并预位灭火瓶',
  'DISCHARGE THE FIRE EXTINGUISHER BOTTLE': '释放灭火瓶',
  'DISCHARGE THE FIRE EXTINGUISHER BOTTLE 1': '释放灭火瓶1',
  'DISCHARGE THE FIRE EXTINGUISHER BOTTLE 2': '释放灭火瓶2',
  'AGENT': '灭火剂', // iniBuilds' own A340 Chinese renders AGENT as 动力机构 here; AGENT is the charge
  'AGENT 1': '灭火剂1',
  'AGENT 2': '灭火剂2',
  'ENG 1 FIRE': '发动机1消防',
  'ENG 2 FIRE': '发动机2消防',
  'TESTS ENGINE, APU, AND MAIN GEAR BAY FIRE DETECTION SYSTEMS': '测试发动机、APU 与主轮舱火警探测',
  'FIRE TEST': '火警测试',
  'EMERN CANCEL GUARD': '紧急取消保护',
  'CANCEL THE AUDIO INDICATOR': '取消音响警告',

  // ---------------------------------------------------------------- instrument lights
  'DOME LIGHTS BRIGHTNESS': '舱顶灯亮度',
  'DOME LT': '舱顶灯',
  'DISPLAY UNIT BRIGHTNESS': '显示组件亮度',
  'DU MASTER BRT': '显示组件总亮度',
  'DU MASTER': '显示组件总控',
  'TOGGLE BRIGHTNESS CONTROL OF ALL THE DISPLAY UNITS': '通断全部显示组件亮度控制',
  'INHIBIT': '抑制',
  'PEDESTAL AND MAIN INSTRUMENT PANEL BRIGHTNESS': '操纵台与主仪表板亮度',
  'FLOOD LT': '泛光灯',
  'INTEGRAL LIGHTS BRIGHTNESS': '整体照明亮度',
  'INTEG LT': '整体照明灯',
  'LIGHT': '灯',
  'TURN ON THE LIGHTS OF ALL THE ANNUNCIATORS': '点亮所有指示器灯',
  'STANDBY COMPASS AND THE EYE REFERENCE LIGHT ON': '备用罗盘与眼位基准灯亮',
  'ICE INDICATOR LIGHT ON': '结冰指示器灯亮',
  'SELECT COMPASS, ICE OR EYE REF LIGHTS': '选择罗盘、结冰或眼位基准灯',
  'STBY COMPASS & EYE REF AND ICE IND': '备用罗盘、眼位基准与结冰指示',
  'REDUCES BRIGHTNESS OF ASSOCIATED DISPLAY UNIT WHEN PRESSED': '按下降低对应显示组件亮度',
  'INCREASES BRIGHTNESS OF ASSOCIATED DISPLAY UNIT WHEN PRESSED': '按下提高对应显示组件亮度',
  'DECREASES CONTRAST OF ASSOCIATED DISPLAY UNIT WHEN PRESSED': '按下降低对应显示组件对比度',
  'INCREASES CONTRAST OF ASSOCIATED DISPLAY UNIT WHEN PRESSED': '按下提高对应显示组件对比度',
  'WHEN PRESSED, TURNS ON OR OFF THE DISPLAY UNIT (DU)': '按下打开通断显示组件',
  'BRIGHTNESS DEC': '亮度减',
  'BRIGHTNESS INC': '亮度加',
  'CONTRAST DEC': '对比度减',
  'CONTRAST INC': '对比度加',
  'BRIGHTNESS CONTROL ON THE ONSIDECONSOLE LIGHTS': '本侧控制台灯亮度控制',
  'CONSOLE LT KNOB': '控制台灯旋钮',
  'BRIGHTNESS OF THE ONSIDE LATERAL CONSOLE LIGHTS': '本侧侧控制台灯亮度',
  'BRIGHTNESS CONTROL ON THE ONSIDE MAP HOLDER LIGHTS': '本侧航图灯亮度控制',
  'MAP LT KNOB': '航图灯旋钮',
  'BRIGHTNESS OF THE ONSIDE MAP HOLDER LIGHTS': '本侧航图灯亮度',
  'TOGGLE THE LIGHTS FOR THE ONSIDE PEDALS': '通断本侧脚蹬灯',
  'PEDALS LT SW': '脚蹬灯电门',
  'ADJUST THE BRIGHTNESS': '调节亮度',
  'BRT/OFF KNOB': '亮度/关断旋钮',

  // ---------------------------------------------------------------- ECAM control panel
  // page names follow fs-base's official Chinese for the same ECAM pages
  'ABN': '非正常',
  'ALL': '全部',
  'BLEED': '引气',
  'COND': '空调',
  'DEFRD': '推迟项目',
  'DISPCH': '放行',
  'DOOR': '舱门',
  'ELAC': 'ELAC 计算机', // kept bare per house style; "ELAC" alone would equal the English
  'ELAC SD PAGE': 'ELAC 系统页',
  'ELDC': 'ELDC（飞控计算机）', // 待实机确认：A350 该计算机全称未在 FCOM/vault 命中
  'ENG': '发动机',
  'FCTL': '飞行操纵',
  'FUEL': '燃油',
  'HYD': '液压',
  'MORE': '更多',
  'PRESS': '客舱增压',
  'RCL ALL': '召回全部',
  'RCL LAST': '召回上次',
  'STS': '状态',
  'TO CONFIG': '起飞构型',
  'VIDEO': '视频',
  // 'WHEEL' is a homograph on this aircraft: eight cursor-control-device keys mean the
  // scroll wheel, one ECAM key means the wheel page. The compiler resolves one English
  // string to one value, so the bare title follows the majority (滚轮, below) and the
  // ECAM page is authored in full rather than composed.
  'WHEEL SD PAGE': '机轮系统页',
  'CHECKLIST LEFT': '左侧检查单',
  'CHECKLIST RIGHT': '右侧检查单',
  'CLEAR LEFT': '清除左屏',
  'CLEAR RIGHT': '清除右屏',
  'CHECKLIST LEFT SD PAGE': '显示左侧检查单页',
  'CHECKLIST RIGHT SD PAGE': '显示右侧检查单页',
  'CLEAR LEFT SD PAGE': '清除左侧显示页',
  'CLEAR RIGHT SD PAGE': '清除右侧显示页',
  'SD DISPLAY SCROLL': '系统显示滚动',
  'SD KNOB': '系统显示旋钮',
  'APU SD PAGE': 'APU 系统页', // "APU" is a preserve token, so the SD PAGE frame cannot see it
  'SCROLL SD PAGE': '滚动系统显示页',
  'ELDC SD PAGE': 'ELDC（飞控计算机）系统页',

  // ---------------------------------------------------------------- EFIS control / ND / PFD
  'DISPLAY THE VOR1 INDICATIONS': '显示 VOR1 指示',
  'DISPLAY THE VOR2 INDICATIONS': '显示 VOR2 指示',
  'BOTH THE ND AND THE VD DISPLAY THE WEATHER': 'ND 与垂直显示器同时显示气象',
  'THE ND DISPLAYS THE TERRAIN PROFILE AND THE TAWS MESSAGES': 'ND 显示地形剖面与近地警告信息',
  'TERRAIN': '地形',
  'ND SHOWS ALL SURROUNDING TRANSPONDER-EQUIPPED AIRCRAFT': 'ND 显示周围装有应答机的航空器',
  'TRAFFIC': '交通',
  'SHOW PFD LANDING SYSTEM DATA': '显示 PFD 着陆系统数据',
  'LS': '着陆系统',
  'ROSE-LS MODE': '罗盘-着陆系统方式',
  'ROSE-VOR MODE': '罗盘-VOR 方式',
  'ROSE-NAV MODE': '罗盘-导航方式',
  'ARC MODE': '弧线方式',
  'PLAN MODE': '计划方式',
  'FOR NAVIGATION PURPOSES SELECT ONE OF THE DISPLAY MODES': '导航时选择一种显示方式',
  'ND MODE SEL': 'ND 方式选择',
  'TURN THE BAROMETRIC REFERENCE KNOB TO SELECT THE QNH VALUE': '旋转气压基准旋钮选择 QNH（修正海压）',
  'STD VALUE': '标准值',
  'BAROMETRIC REFERENCE KNOB': '气压基准旋钮',
  'SELECT THE BAROMETRIC UNIT (HPA OR INHG)': '选择气压单位（百帕或英寸汞柱）',
  'BAROMETRIC REFERENCE SELECTOR': '气压基准选择器',
  'ZOOM': '缩放',
  'SELECT THE RANGE OF THE ND AND THE VD': '选择 ND 与垂直显示器的距离范围',
  'ND RANGE SEL': 'ND 范围选择',
  'DISPLAY THE ETACS VIDEO': '显示舱门摄像系统画面', // 待实机确认：ETACS 全称包内未展开
  'DISPLAYS CONSTRAINTS FOR FLIGHT PLAN WAYPOINTS': '显示航路点高度/速度限制',
  'CONSTRAINTS': '航路限制',
  'ND SHOWS WAYPOINTS FROM NAV AND PILOT STORED DATABASES': 'ND 显示导航库与机组存储的航路点',
  'WAYPOINTS': '航路点',
  'ND SHOWS VORs, DMEs, AND PILOT-STORED NAVAIDS': 'ND 显示 VOR、DME 与机组存储导航台',
  'NAVAIDS': '导航台',
  'ND SHOWS ALL NDBs FROM NAVIGATION DATABASE': 'ND 显示导航库中全部无方向信标台',
  'NDBS': '无方向信标台',
  'ND SHOWS ALL AIRPORTS FROM DATABASE EXCEPT ORIGIN/DEST': 'ND 显示除起讫机场外全部机场',
  'AIRPORTS': '机场',
  'SHOW PFD VELOCITY VECTOR': '显示 PFD 航迹矢量',
  'VV': '航迹矢量',

  // ---------------------------------------------------------------- electrical overhead
  'THE BATTERY IS CONNECTED TO THE NETWORK': '电池接入电网',
  'BAT EMER 1': '电池1应急供电',
  'BAT EMER 2': '电池2应急供电',
  'BAT SELECTOR': '电池选择器',
  'DISPLAY THE ASSOCIATED VOLTAGE': '显示对应电压',
  'THE BUS TIE CONTACTORS': '汇流条连接接触器',
  'ELECTRICAL STATUS OF ALL COMMERCIAL LOADS (LEFT)': '左侧商用负载电气状态',
  'ELECTRICAL STATUS OF ALL COMMERCIAL LOADS (RIGHT)': '右侧商用负载电气状态',
  'COMMERCIAL 1': '商用负载1',
  'COMMERCIAL 2': '商用负载2',
  'STATUS OF THE AUTOMATIC SHEDDING FUNCTION': '自动卸载功能状态',
  'ELM': 'ELM（电气负载管理）',
  'CONNECT THE EXTERNAL POWER TO THE ELECTRICAL NETWORK': '将外部电源接入电网',
  'EXT 1': '外部电源1',
  'EXT 2': '外部电源2',
  'GALLEY ELECTRICAL STATUS': '厨房电气状态',
  'GALLEY': '厨房',
  'DISCONNECT THE ENGINE GENERATOR FROM THE ELECTRICAL NETWORK': '将发动机发电机从电网断开',
  'DISCONNECT THE APU GENERATOR FROM THE ELECTRICAL NETWORK': '将 APU 发电机从电网断开',
  'DISCONNECT THE ENGINE GENERATOR FROM THE ENGINE': '断开发电机与发动机的机械连接',
  'GEN 1A': '发电机1A',
  'GEN 1B': '发电机1B',
  'GEN 2A': '发电机2A',
  'GEN 2B': '发电机2B',
  'DRIVE 1A': '驱动脱开1A',
  'DRIVE 1B': '驱动脱开1B',
  'DRIVE 2A': '驱动脱开2A',
  'DRIVE 2B': '驱动脱开2B',
  'IFE CENTER AND PASSENGER SEATS ELECTRICAL STATUS': '娱乐系统与旅客座椅电气状态',
  'STATUS OF SIDE 1&2 EPDC ISOLATION': '1、2 侧配电中心隔离状态',
  'SIDE 1&2 ISOL': '1、2 侧隔离',
  'EMERGENCY LOCATOR TRANSMITTER (ELT)': '应急定位发射机',
  'OPEN TO SET ELT ON': '打开护罩以开启应急定位发射机',
  'TOGGLE THE AUTO EMER DESCENT FUNCTION': '通断自动应急下降功能',
  'EMER DESCENT': '应急下降',
  'RAT INDICATOR': 'RAT 指示器',
  'EMER GEN FAULT LIGHT': '应急发电机故障灯',
  'EXTEND THE RATK': '放出 RAT',
  'EXTEND': '放出',
  'RAT MAN ON': 'RAT 人工放出',
  'EMER 1': '应急汇流条1', // positions of MAINT_ELEC_BAT_VOLTAGE_SELECTOR, not supplies
  'EMER 2': '应急汇流条2',
  'MAINT DC SUPPLY CONTROL': '维护直流供电控制',
  'ELEC REMOTE C/B': '电气远程跳开关',
  'ELEC PANEL': '电气面板',
  'FADEC ELECTRICAL SUPPLY': 'FADEC 供电',
  'ENG 1 FADEC GND PWR': '发动机1 FADEC 地面电源',
  'ENG 2 FADEC GND PWR': '发动机2 FADEC 地面电源',
  'INITIATE OR ABORT REFUELING': '开始或中断加油',
  'REFUEL': '加油',
  'TOGGLE HF DATA COMMUNICATION': '通断 HF 数据通信',
  'TOGGLE SERVICE INTERPHONE': '通断服务内话',
  'SVCE INT OVRD': '服务内话超控',
  'TOWING NETWORK SUPPLY': '牵引电网供电',
  'TOWING ON BAT': '电池牵引供电',
  'TOGGLE PORTABLE MAINTENANCE ACCESS CONNECTION': '通断便携式维护共地接口',
  'COM GND CONNECTION': '共地接口连接',
  'TOGGLE APU ECONOMIC MODE': '通断 APU 经济方式',
  'APU ECON MODE': 'APU 经济方式',
  'CONTROL THE CABIN EMERGENCY LIGHTS': '控制客舱应急灯',
  'ON (emergency lights are on)': '开启（应急灯亮）',
  'EMER EXIT LT': '应急出口灯',

  // ---------------------------------------------------------------- engines / thrust
  'CONTROL THE MANUAL START SEQUENCE OF THE ASSOCIATED ENGINE': '控制对应发动机的人工起动程序',
  'ENG 1 MAN START': '发动机1人工起动',
  'ENG 2 MAN START': '发动机2人工起动',
  'ENGINE 1 MASTER LEVER': '发动机1主电门',
  'ENGINE 2 MASTER LEVER': '发动机2主电门',
  'ENG 1 MASTER LEVER': '发动机1主电门',
  'ENG 2 MASTER LEVER': '发动机2主电门',
  'SELECT ENGINE START MODE': '选择发动机起动方式',
  'ENG START SELECTOR': '发动机起动方式选择器',
  'PUSH TO DISCONNECT AUTOTHRUST': '按下断开自动推力',
  'A/THR DISCONNECT': '自动推力断开',
  'A/THR': '自动推力',
  'INTERFACE WITH THE A/THR VIA THE THRUST LEVER': '通过推力手柄与自动推力交联',
  'ENG 1 - THRUST LEVER': '发动机1推力手柄',
  'ENG 2 - THRUST LEVER': '发动机2推力手柄',

  // ---------------------------------------------------------------- evacuation command
  'ONLY THE CAPTAIN CAN ORDER THE EVACUATION': '仅机长可下达撤离指令',
  'CAPTAIN OR PURSER CAN ORDER THE EVACUATION': '机长或乘务长可下达撤离指令',
  'THE CAPTAIN OR THE CHIEF PURSER CAN ORDER THE EVACUATION': '机长或乘务长可下达撤离指令',
  'ENABLE EVAC ORDER SELECTOR': '启用撤离指令选择器',
  'CAPT AND PURS SWITCH': '机长与乘务长电门',
  'ORDER AN EVACUATION': '下达撤离指令',
  'COMMAND': '撤离指令',
  'WHEN PRESSED, THE HORN GOES OFF IN THE COCKPIT': '按下后驾驶舱撤离喇叭停止',
  'HORN OFF': '喇叭停止',

  // ---------------------------------------------------------------- fly-by-wire computers
  'SELECT FLAPS CONFIG': '选择襟翼构型',
  'PRIMARY FLIGHT CONTROL AND GUIDANCE COMPUTER 1': '飞行控制与引导主计算机1',
  'PRIMARY FLIGHT CONTROL AND GUIDANCE COMPUTER 2': '飞行控制与引导主计算机2',
  'PRIMARY FLIGHT CONTROL AND GUIDANCE COMPUTER 3': '飞行控制与引导主计算机3',
  'SECONDARY FLIGHT CONTROL COMPUTER 1': '飞行控制次计算机1',
  'SECONDARY FLIGHT CONTROL COMPUTER 2': '飞行控制次计算机2',
  'SECONDARY FLIGHT CONTROL COMPUTER 3': '飞行控制次计算机3',
  'F/CTL PRIM 1': '飞行操纵主计算机1',
  'F/CTL PRIM 2': '飞行操纵主计算机2',
  'F/CTL PRIM 3': '飞行操纵主计算机3',
  'F/CTL SEC 1': '飞行操纵次计算机1',
  'F/CTL SEC 2': '飞行操纵次计算机2',
  'F/CTL SEC 3': '飞行操纵次计算机3',
  'SPEED BRAKE LEVER': '减速板手柄',
  'SPEED BRAKE': '减速板',
  'CONTROL THE POSITION OF THE THS': '控制水平安定面配平位置',
  'THS': '水平安定面配平',
  'ENGAGE OR DISENGAGE THE CAPTAIN TILLER DISCONNECT': '接通或断开机长手轮脱开',
  'CAPTAIN TILLER DISCONNECT': '机长手轮脱开',
  'ENGAGE OR DISENGAGE THE FO TILLER DISCONNECT': '接通或断开副驾驶手轮脱开',
  'FO TILLER DISCONNECT': '副驾驶手轮脱开',
  'TILLER DISCONNECT': '手轮脱开',
  'ENGAGE': '接通',
  'DISENGAGE': '断开',
  'PRESS TO DISCONNECT THE AUTOPILOT OR TAKE CONTROL': '按下断开自动驾驶或接管操纵',
  'SIDESTICK PUSH BUTTON': '侧杆按钮',
  'CONTROLS THE RUDDER TRIM POSITION': '控制方向舵配平位置',
  'RESET THE RUDDER TRIM POSITION': '重置方向舵配平位置',

  // ---------------------------------------------------------------- AFS control panel (FCU)
  'WHEN PRESSED, THE AIRCRAFT IMMEDIATELY STARTS TO LEVEL-OFF. NOTE: THE ALT PB ALSO COMES ON, WHEN THE AIRCRAFT MAINTAINS A SELECTED OR MANAGED ALTITUDE': '按下后飞机立即开始改平。保持选定或管理高度时高度灯也亮',
  'SET THE TARGET ALTITUDE ON THE AFS CP': '在自动飞行控制面板设定目标高度',
  'ACTIVATE THE SELECTED TARGET ALTITUDE ON THE AFS CP': '激活自动飞行面板上选定的目标高度',
  'ALTITUDE TARGET SET TO MANAGED IF LATERAL GUIDANCE IS MANAGED': '横向引导为管理式时高度目标转为管理',
  'ALT KNOB': '高度旋钮',
  'SET THE TARGET ALTITUDE IN INCREMENTS OF 100 FT OR 1.000 FT': '以100英尺或1000英尺步进设定目标高度',
  'WHEN PRESSED, DISARMS OR DISENGAGES THE APPROACH MODES': '按下解除或断开进近方式',
  'WHEN PRESSED, ENGAGES AP1': '按下接通自动驾驶1',
  'WHEN PRESSED, ENGAGES AP2': '按下接通自动驾驶2',
  'AP 1': '自动驾驶1',
  'AP 2': '自动驾驶2',
  'WHEN PRESSED, ARMS OR ACTIVATES THE A/THR': '按下预位或激活自动推力',
  'WHEN PRESSED, ENGAGES FD1 AND FD2': '按下接通飞行指引1和2',
  'FD': '飞行指引',
  'ND CHRONO: STARTS (1 PRESS), STOPS (2), RESETS (3)': 'ND 计时器：按一次启动、两次停止、三次复位',
  'BRIGHTNESS OF THE EFIS CP AND AFS CP': 'EFIS 与自动飞行控制面板亮度',
  'FCU BRIGHTNESS KNOB LEFT': 'FCU 亮度旋钮（左）',
  'FCU BRIGHTNESS KNOB RIGHT': 'FCU 亮度旋钮（右）',
  'BRIGHTNESS OF THE LABELS': '字符亮度',
  'PRESELECT A HEADING OR A TRACK TARGET': '预选航向或航迹目标',
  'ACTIVATES THE SELECTED HEADING OR TRACK TARGET': '激活选定的航向或航迹目标',
  'A MANAGED LATERAL MODE ARMS OR ENGAGES': '预位或接通管理式横向方式',
  'HDG/TRK KNOB': '航向/航迹旋钮',
  'ROTATE TO INCREASE/DECREASE HUD BRIGHTNESS': '旋转调节平视显示器亮度',
  'CAPT HUD BRIGHTNESS': '机长平视显示器亮度',
  'FO HUD BRIGHTNESS': '副驾驶平视显示器亮度',
  'CAPT HUD': '机长平视显示器',
  'FO HUD': '副驾驶平视显示器',
  'CAPT HUD COVER': '机长平视显示器护罩',
  'FO HUD COVER': '副驾驶平视显示器护罩',
  'AUTOLAND': '自动着陆',
  'TOGGLE DECLUTTER MODE': '通断平显简化显示方式',
  'CAPT HUD DECLUTTER': '机长平显简化显示',
  'FO HUD DECLUTTER': '副驾驶平显简化显示',
  'X-WIND': '侧风',
  'TOGGLE HUD X-WIND MODE ON': '接通平视显示器侧风方式',
  'CAPT HUD X-WIND MODE SWITCH': '机长平显侧风方式电门',
  'FO HUD X-WIND MODE SWITCH': '副驾驶平显侧风方式电门',
  'DISARMS/DISENGAGES APPROACH MODES (LOC, F/LOC, LOC B/C)': '解除/断开进近方式（LOC、F/LOC、LOC B/C）',
  'LOC': '航道截获',
  'THE LOUDSPEAKER VOLUME IS ADJUSTED BY TURNING THE KNOB': '旋转旋钮调节扬声器音量',
  'LOUDSPEAKER VOLUME CONTROL KNOB': '扬声器音量旋钮',
  'ECAM LEVEL 2 CAUTION: MASTER CAUT LIGHT ON, CHIME SOUNDS': '二级警戒：主警戒灯亮并响谐音',
  'ECAM WARNING: MASTER WARN LIGHT FLASHES, AUDIO SOUNDS': '警告：主警告灯闪烁并发出音响',
  'PUSH TO RESET': '按下复位',
  'MASTER CAUTION': '主警戒',
  'MASTER WARNING': '主警告',
  'DISPLAYS THE CURRENT AND TARGET ALTITUDES IN METERS (IN ADDITION TO FEET) ON THE PFDS': '在 PFD 上以米显示当前与目标高度',
  'ONLY FEET': '仅显示英尺',
  'SHOWING METERS': '显示米制',
  'METER': '米制',
  'PRESELECT A SPEED OR MACH TARGET': '预选速度或马赫目标',
  'ACTIVATES THE SELECTED SPEED OR MACH TARGET': '激活选定的速度或马赫目标',
  'THE SPEED OR MACH BECOMES MANAGED': '速度或马赫转为管理',
  'SPD/MACH KNOB': '速度/马赫旋钮',
  'SPD/MACH PB TOGGLES SPEED TARGET BETWEEN IAS AND MACH': '在指示空速与马赫之间切换速度目标',
  'SPD/MACH': '速度/马赫',
  'TOGGLE BETWEEN HDG-V/S AND TRK-FPA': '切换航向-垂直速度与航迹-航径角',
  'HDG-V/S': '航向/垂直速度',
  'TRK-FPA': '航迹/航径角',
  'HDG-V/S / TRK-FPA': '航向-垂直速度/航迹-航径角',
  'WINDOW SHOWS HDG/TRK (MAG NORTH); PRESS FOR TRUE NORTH': '窗口显示航向/航迹（磁北），按下换真北',
  'MAG NORTH': '磁北',
  'TRUE NORTH': '真北',
  'TRUE/MAG': '真/磁北',
  'PRESELECT A VERTICAL SPEED OR FLIGHT PATH ANGLE TARGET': '预选垂直速度或航径角目标',
  'ACTIVATES SELECTED VERTICAL SPEED OR FLIGHT PATH ANGLE': '激活选定的垂直速度或航径角',
  'ACTIVATES SELECTED V/S OR FPA TO HOLD 0 FT/MIN OR 0°': '激活选定垂直速度/航径角并保持零',
  'V/S / FPA KNOB': '垂直速度/航径角旋钮',
  'FLASHES FOR ATC MESSAGE OR AUTOMATIC MAILBOX REMINDER': '有 ATC 报文或自动信箱提醒时闪烁',
  'MSG': '报文',
  'ATC MSG': 'ATC 报文',

  // ---------------------------------------------------------------- fuel
  'FUEL CROSSFEED VALVE': '燃油交输活门',
  'CROSSFEED A': '交输活门A',
  'CROSSFEED B': '交输活门B',
  'CENTER TANK PUMP': '中央油箱泵',
  'CTR TK FEED': '中央油箱供油',
  'CENTER LEFT TANK PUMP': '中央油箱左侧泵',
  'CTR TK L': '中央油箱左',
  'CENTER RIGHT TANK PUMP': '中央油箱右侧泵',
  'CTR TK R': '中央油箱右',
  'LEFT TANK MAIN PUMP': '左主油箱泵',
  'L TK MAIN': '左主油箱泵',
  'LEFT TANK STANDBY PUMP': '左油箱备用泵',
  'L TK STBY': '左油箱备用泵',
  'RIGHT TANK MAIN PUMP': '右主油箱泵',
  'R TK MAIN': '右主油箱泵',
  'RIGHT TANK STANDBY PUMP': '右油箱备用泵',
  'R TK STBY': '右油箱备用泵',
  'TRANSFER PATH BETWEEN THE WING TANK AND THE CENTER TANK': '翼油箱与中央油箱间的传输通道',
  'L TK XFR': '左油箱传输',
  'R TK XFR': '右油箱传输',
  'FFI CTL': '燃油量指示器控制',
  'OPEN FUEL JETTISON VALVE': '打开抛油活门',
  'FUEL JETTISON ACTIVATE': '抛油作动',
  'FUEL JETTISON ARM': '抛油预位',
  'ARM FUEL JETTISON BEFORE ACTIVATING': '作动前先预位抛油',

  // ---------------------------------------------------------------- hydraulics
  'GREEN ELECTRIC PUMP FAULT PUSH BUTTON': '绿系统电动泵故障按钮',
  'GREEN ELEC PMP': '绿电动泵',
  'GREEN ELECTRIC PUMP AUTO PUSH BUTTON': '绿系统电动泵自动按钮',
  'GREEN ELEC PMP AUTO': '绿电动泵自动',
  'YELLOW ELECTRIC PUMP FAULT PUSH BUTTON': '黄系统电动泵故障按钮',
  'YELLOW ELEC PMP': '黄电动泵',
  'YELLOW ELECTRIC PUMP AUTO PUSH BUTTON': '黄系统电动泵自动按钮',
  'YELLOW ELEC PMP AUTO': '黄电动泵自动',
  'TOGGLE GREEN ENG 1 PUMP': '通断绿系统发动机1泵',
  'GREEN ENG 1 PUMP': '绿系统发动机1泵',
  'TOGGLE GREEN ENG 2 PUMP': '通断绿系统发动机2泵',
  'GREEN ENG 2 PUMP': '绿系统发动机2泵',
  'TOGGLE YELLOW ENG 1 PUMP': '通断黄系统发动机1泵',
  'YELLOW ENG 1 PUMP': '黄系统发动机1泵',
  'TOGGLE YELLOW ENG 2 PUMP': '通断黄系统发动机2泵',
  'YELLOW ENG 2 PUMP': '黄系统发动机2泵',
  'HYDRAULIC CIRCUIT, EDP AND FSOV INDICATION': '液压回路、发动机驱动泵与关断活门指示',
  'GREEN ENG 1 SUPPLY': '绿系统发动机1供压',
  'GREEN ENG 2 SUPPLY': '绿系统发动机2供压',
  'YELLOW ENG 1 SUPPLY': '黄系统发动机1供压',
  'YELLOW ENG 2 SUPPLY': '黄系统发动机2供压',
  'REINFLATE THE BRAKE ACCUMULATORS': '刹车蓄压器再充压',
  'ACCU REINFLATE': '蓄压器再充压',

  // ---------------------------------------------------------------- landing gear / brakes
  'EXTEND OR RETRACT LANDING GEAR': '放下或收上起落架',
  'LANDING GEAR': '起落架',
  'EXTEND LANDING GEAR BY GRAVITY': '重力放下起落架',
  'L/G GRVTY EXTN': '起落架重力放下',
  'OPEN COVER': '打开护罩',
  'L/G GRVTY EXTN COVER': '起落架重力放下护罩',
  'GRAVITY GEAR GUARD': '重力放起落架保护',
  'PARKING BRAKE HANDLE': '停机刹车手柄',
  'PARK BRK': '停机刹车',
  'NOSE UP': '机头上仰',
  'NOSE DOWN': '机头下俯',
  'TOGGLE AIRCRAFT ANTI SKID SYSTEM': '通断飞机防滑系统',
  'ANTI SKID': '防滑',
  'TOGGLE AIRCRAFT AUTOBRAKE SYSTEM': '通断自动刹车系统',
  'A/BRK': '自动刹车',
  'BRAKE FANS SPEED UP BRAKE COOLING TO REDUCE TURNAROUND TIME': '刹车风扇加速冷却以缩短过站时间',
  'BRAKE FANS': '刹车风扇',
  'SETS THE RUNWAY CONDITION OR BRAKING ACTION': '设定跑道状况或刹车作用',
  'SETS THE RUNWAY CONDITION OR BRAKING ACTION VALUE': '设定跑道状况或刹车作用值',
  'RWY COND': '跑道状况',
  'BRAKING ACTION': '刹车作用',
  'RWY COND/BRAKING ACTION SELECTOR': '跑道状况/刹车作用选择器',
  'RWY COND/BRAKING ACTION KNOB': '跑道状况/刹车作用旋钮',
  'RWY CONDITION / BRAKING ACTION MATRIX APPEARS ON THE SD': 'SD 上显示跑道状况/刹车作用矩阵',
  'RWY CONDITION / BRAKING ACTION MATRIX DISAPPEARS': '跑道状况/刹车作用矩阵消失',

  // ---------------------------------------------------------------- exterior lights
  'TOGGLE DOME LIGHTS': '通断舱顶灯',
  'BEACON': '信标灯',
  'LOGO': '标志灯',
  'STROBE': '频闪灯',
  'NOSE': '前起落架灯',
  'WING': '机翼检查灯',
  'SETS LOGO LIGHT MODE; AUTO ON GND OR IN FLIGHT WITH SLATS EXTENDED': '设定标志灯方式；地面或缝翼放出时自动',
  'SETS STROBE LIGHT MODE; AUTO FLASHES LIGHTS IN FLIGHT': '设定频闪灯方式；空中自动闪烁',
  'NAV LT 1 IS ACTIVE AND THE NAVIGATION LIGHTS ARE ON': '航行灯1工作，航行灯点亮',
  'NAV LT 2 IS ACTIVE AND THE NAVIGATION LIGHTS ARE ON': '航行灯2工作，航行灯点亮',
  'SELECT NAVIGATION LIGHTS MODE': '选择航行灯方式',
  'SELECT NOSE LANDING GEAR LIGHTS MODE': '选择前起落架灯方式',
  'T.O: TAKEOFF, TAXI AND RWY TURN OFF LIGHTS ON': '起飞位：起飞、滑行与跑道脱离灯亮',
  'TOGGLE WING AND ENGINE SCAN LIGHTS': '通断机翼与发动机检查灯',

  // ---------------------------------------------------------------- FMS / MCDU keyboard
  'INSERT A NUMBER': '插入数字',
  'INSERTS A CHARACTER': '插入字符',
  'INSERTS AN ALPHABET CHARACTER AT THE CURSOR POSITION IN THE ENTRY FIELD': '在输入项光标处插入字母',
  'INSERTS A SPACE AT THE CURSOR POSITION IN THE ENTRY FIELD': '在输入项光标处插入空格',
  'INSERT': '插入',
  'CLEAR THE CHARACTER THAT IS ON THE LEFT OF THE CURSOR': '清除光标左侧字符',
  'CLEAR THE FMS MESSAGE': '清除飞行管理报文',
  'CLR INFO': '清除信息',
  'MOVE THE CURSOR': '移动光标',
  'UP DIRECTION ARROW': '方向键上',
  'DOWN DIRECTION ARROW': '方向键下',
  'LEFT DIRECTION ARROW': '方向键左',
  'RIGHT DIRECTION ARROW': '方向键右',
  'EDIT AN ENTRY FIELD, OPTION-LIST OR ACTIVATE A BUTTON': '编辑输入项、选项表或激活按键',
  'DISPLAY THE ATC COM REQUEST PAGE ON THE MFD': '在多功能显示器显示 ATC 请求页',
  'ATC COM': 'ATC 通信',
  'DISPLAYS BOTTOM OF FLIGHT PLAN ON FMS ACTIVE/F-PLN PAGE (MFD)': '在飞行计划页显示下半部（多功能显示器）',
  'DISPLAYS TOP OF FLIGHT PLAN ON FMS ACTIVE/F-PLN PAGE (MFD)': '在飞行计划页显示上半部（多功能显示器）',
  'DISPLAY THE FMS ACTIVE/INIT PAGE ON THE MFD': '在多功能显示器显示初始化页',
  'DISPLAY THE FMS ACTIVE/PERF PAGE ON THE MFD': '在多功能显示器显示性能页',
  'DISPLAY THE FMS DIRECT TO PAGE ON THE MFD': '在多功能显示器显示直飞页',
  'DISPLAY THE FMS POSITION/NAVAIDS PAGE ON THE MFD': '在多功能显示器显示位置/导航台页',
  'DISPLAY THE FMS SEC INDEX PAGE ON THE MFD': '在多功能显示器显示备份计划索引页',
  'Display the SURV/CONTROLS page on the MFD': '在多功能显示器显示监控/控制页',
  'ACTIVATE THE NOTE PAD AREA ON THE MFD': '激活多功能显示器的记事区',
  'MOVE THE CURSOR TO THE MAILBOX': '将光标移至信息框',
  'MOVE THE CURSOR TO THE ONSIDE MFD': '将光标移至本侧多功能显示器',
  'MOVE THE CURSOR TO THE ONSIDE ND': '将光标移至本侧 ND',
  'MOVE THE CURSOR TO THE ONSIDE OIS DISPLAY': '将光标移至本侧信息服务器显示',
  'DEST': '目的地',
  'DIR': '直飞',
  'F-PLN': '飞行计划',
  'INIT': '初始化',
  'PERF': '性能',
  'SEC INDEX': '备份计划索引',
  'NAVAID': '导航台',
  'NOTE PAD': '记事本',
  'MAIL BOX': '信息框',
  'SURV': '监控',
  'OIS': 'OIS（机上信息服务器）',
  '" . " KEY': '小数点键',

  // ---------------------------------------------------------------- OIS / cabin connectivity
  'EFB': 'EFB（电子飞行包）',
  'AVNCS': '航电设备',
  'SELECT THE DESIRED OIS DISPLAY MODE': '选择信息服务器显示方式',
  'OIS SW': '信息服务器电门',
  'TOGGLE THE PASSENGER SERVICES TO THE OIS CONNECTION': '通断旅客服务与信息服务器连接',
  'CAB DATA TO OIS': '客舱数据至信息服务器',
  'TOGGLE THE OIS CAB & MAINT SERVER': '通断信息服务器客舱与维护功能',
  'OIS DATA TO AVNCS': '信息服务器数据至航电',
  'TOGGLE THE WIRELESS AIRPORT COMMUNICATION SYSTEM (WACS)': '通断机场无线通信系统',
  'GATELINK': '登机口无线链路',
  'DUE TO A CHANGE IN THE STANDARD DISPLAY CONFIGURATION, THE FLIGHT CREW CAN CHANGE THE DISPLAY OF ONE OF THE ONSIDE D': '标准显示构型改变后，机组可切换本侧显示器的显示内容',
  'DISPLAY CYCLE': '显示切换',
  'DISPLAY OIS ON THE CENTER LOWER DU': '在中下显示器显示信息服务器',
  'DISPLAY OIS ON THE ONSIDE DU': '在本侧显示器显示信息服务器',
  'OIS VIEW OFFSIDE': '查看对侧信息服务器',
  'CAPT OIS ON CENTER': '机长信息服务器至中央',
  'FO OIS ON CENTER': '副驾驶信息服务器至中央',
  'TOGGLE ROW/ROP AND BTV': '通断旅客点播与机上电视', // 待实机确认：ROW/ROP 与 BTV 包内未展开
  'ROW/ROP': '旅客点播',

  // ---------------------------------------------------------------- oxygen
  'CONTROLS OXYGEN SUPPLY TO THE MASKS IN THE COCKPIT': '控制驾驶舱面罩供氧',
  'CREW SUPPLY': '机组供氧',
  'DROP THE CABIN MASKS': '释放客舱面罩',
  'CABIN MASKS DROP': '客舱面罩释放',
  'EMERGENCY OXYGEN': '应急氧气',
  'EMERGENCY': '应急',
  'EMER PRESSURE SEL': '应急压力选择',
  'OXYGEN PERCENTAGE': '氧气百分比',
  'PUSH TO TEST': '按下测试',
  'OXYGEN MASK TEST': '氧气面罩测试',
  'OXYGEN RESET': '氧气系统复位',
  'MAINT OXYGEN RESET': '维护态氧气复位',

  // ---------------------------------------------------------------- recorder / printer
  'PRINTER': '打印机',
  'PRINTS A SPECIFIC ACMS REPORT': '打印指定 ACMS 报告',
  'ACMS TRIGGER': 'ACMS 触发',
  'RECORD AN EVENT IN THE DATA OF BOTH THE DFDR AND THE VQAR': '在飞行数据记录器与快速存取记录器中标记事件',
  'MANUALLY START THE RECORDER SYSTEM AND THE CV': '人工起动记录系统与语音记录器',
  'RCDR GND CTL': '记录器地面控制',

  // ---------------------------------------------------------------- audio control panel (RMP)
  'ACTIVATION/DIALING KEY': '启用/拨号键',
  'ADK 2': '发码键2',
  'ADK 3': '发码键3',
  'TRANSMISSION KEY': '发射键',
  'CAB TRANSMISSION KEY': '客舱发射键',
  'CAB': '客舱',
  'CAB KNOB': '客舱旋钮',
  'INT TRANSMISSION KEY': '内话发射键',
  'INT KNOB': '内话旋钮',
  'PA TRANSMISSION KEY': '旅客广播发射键',
  'PA KNOB': '旅客广播旋钮',
  'HF1 TRANSMISSION KEY': 'HF1 发射键',
  'HF1 KNOB': 'HF1 旋钮',
  'HF2 TRANSMISSION KEY': 'HF2 发射键',
  'HF2': '高频2', // radio keycap titles cannot stay identical to the English: the compiler
  'HF2 KNOB': 'HF2 旋钮', // rejects a pattern output equal to its input, so spell them out
  'VHF1 TRANSMISSION KEY': 'VHF1 发射键',
  'VHF1': '甚高频1',
  'VHF1 KNOB': 'VHF1 旋钮',
  'VHF2 TRANSMISSION KEY': 'VHF2 发射键',
  'VHF2': '甚高频2',
  'VHF2 KNOB': 'VHF2 旋钮',
  'VHF3 TRANSMISSION KEY': 'VHF3 发射键',
  'VHF3': '甚高频3',
  'VHF3 KNOB': 'VHF3 旋钮',
  'TEL1 TRANSMISSION KEY': '电话1发射键',
  'TEL1': '电话1',
  'TEL1 KNOB': '电话1旋钮',
  'TEL1 RECEPTION KNOB': '电话1接收旋钮',
  'TEL2 TRANSMISSION KEY': '电话2发射键',
  'TEL2': '电话2',
  'TEL2 KNOB': '电话2旋钮',
  'TEL2 RECEPTION KNOB': '电话2接收旋钮',
  'VOICE RECEPTION KNOB': '语音接收旋钮',
  'VOICE KNOB': '语音旋钮',
  'BOOMSET SELECTOR': '话筒/耳机选择器',
  'INT/RAD': '内话/无线电',
  'TOGGLE RECEPTION': '通断接收',
  'DOWN KEY': '下降键',
  'UP KEY': '上升键',
  'LOAD KEY': '装载键',
  'LOAD': '装载',
  'RESET KEY': '复位键',
  'LINE SELECTION KEY': '行选键',
  'LSK 1': '行选键1',
  'LSK 2': '行选键2',
  'LSK 3': '行选键3',
  'MESSAGE CLEAR KEY': '报文清除键',
  'MSG CLR': '报文清除',
  'PERIOD': '小数点',
  'ADF 1': 'ADF 电台1',
  'VOR 1': 'VOR 导航台1',
  'VOR 2': 'VOR 导航台2',
  'RAD NAV': '无线电导航',
  'SQWK': '应答机代码',
  'SEAT BELTS': '系好安全带',
  'FASTEN SEAT BELT AND RETURN TO SEAT SIGNS': '系好安全带与回座信号灯',
  'NO MOBILE SIGNS': '禁止使用手机信号灯',
  'NO MOBILE': '禁止手机',
  'NO SMOKING AND NO PORTABLE ELECTRONIC DEVICES SIGNS': '禁止吸烟与便携电子设备信号灯',
  'NO SMKG/NO PED': '禁烟/禁电子设备',
  'TOGGLE THE ECAM T.O SURV ALERTS': '通断起飞监控警告',
  'TOGGLE G/S MODE (MODE 5)': '通断下滑道方式（方式5）',
  'G/S MODE': '下滑道方式',
  'DISPLAY TCAS IN THE ABOVE MODE': '在上方显示 TCAS',
  'DISPLAY TCAS IN THE BELOW MODE': '在下方显示 TCAS',
  'TOGGLE TCAS IN TA/RA OR TA ONLY MODE': '切换 TCAS 交通咨询/决断咨询方式',
  'one': '一档',
  'twp': '二档', // vendor typo for "two": pedal position legend

  // ---------------------------------------------------------------- windshield / wiper / radar
  'CONTROL WINDSHIELD WIPER SPEED': '控制风挡雨刷速度',
  'WIPER SELECTOR': '雨刷选择器',
  'INTERMITTENT SLOW': '间歇-慢',
  'INTERMITTENT MEDIUM': '间歇-中',
  'INTERMITTENT FAST': '间歇-快',
  'REPELLENT FLUID': '排雨剂',
  'RAIN REPELLENT': '排雨剂',
  'WX RADAR TILT': '气象雷达倾角',
  'MANUAL MODE': '人工方式',
  'AUTO MODE': '自动方式',
  'ELEVN': '俯仰稳定',
  'GAIN': '增益',
  'SYS 1 WXR FUNCTION': '系统1气象雷达功能',
  'WXR SYS 1': '气象雷达1',
  'SYS 2 WXR FUNCTION': '系统2气象雷达功能',
  'WXR SYS 2': '气象雷达2',
  'VERTICAL DISPLAY AZIMUTH': '垂直显示方位',
  'VD AZIM': '垂直显示方位',
  'SYS 1 XPDR FUNCTION': '系统1应答机功能',
  'XPDR SYS 1': '应答机1',
  'SYS 2 XPDR FUNCTION': '系统2应答机功能',
  'XPDR SYS 2': '应答机2',
  'XPDR SYS': '应答机系统',
  'SYS 1 NAV FUNCTION': '系统1导航功能',
  'NAV SYS 1': '导航系统1',
  'SYS 2 NAV FUNCTION': '系统2导航功能',
  'NAV SYS 2': '导航系统2',
};

/** Escape a source string for use as an anchored literal regex. */
const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Resolve an authored label, or null when nothing was authored. */
const zh = (en) => EXACT[n(en)] ?? null;

/** Append a Chinese suffix, inserting a space only after a Latin/digit tail. */
const tail = (base, suffix) => base + (/[A-Za-z0-9]$/.test(base) ? ' ' + suffix : suffix);

const FRAMES = [
  // "<label> SD PAGE" — ECAM control key action line; page name must itself be authored.
  [/^(.+?) SD PAGE$/, (m) => {
    const z = zh(m[1]);
    return z ? tail(z, '系统页') : null;
  }],
  // "<label> GUARD" — same composition the generator's frame does, but over THIS table
  // (it can only see its own EXACT object). iniBuilds writes GUARD as 保护 with no gap,
  // matching its own "FLT CTL PRIM1 GUARD" -> 飞行操纵主计算机1保护.
  [/^(.+?) GUARD$/, (m) => {
    const z = zh(m[1]);
    return z ? z + '保护' : null;
  }],
  // "SET <label>" — iniBuilds writes 设置<label>.
  [/^SET (.+)$/, (m) => {
    const z = zh(m[1]);
    return z ? '设置' + z : null;
  }],
  // MCDU / sliding-table keycaps: "A", "Z", "7". Never bare, so the audit sees Chinese.
  [/^([A-Z])$/, (m) => `${m[1]} 键`],
  [/^([0-9])$/, (m) => `${m[1]} 键`],
];

export const PATTERNS = [
  // Authored literals published as anchored patterns first, so an explicitly worded string
  // always beats a compositional frame below it. They still sit last in the generator's
  // chain, so termbase/sibling evidence wins wherever it exists. Header note explains why
  // these cannot rely on the EXACT merge.
  ...Object.entries(EXACT).map(([en, val]) => [new RegExp('^' + esc(en) + '$'), () => val]),
  ...FRAMES,
];
